import { useEffect, useMemo, useState } from "react";
import { useModalKeys } from "../hooks/useModalKeys";
import { onMarkdownLinkClick, renderMarkdown } from "../lib/mdHtml";
import ModalBackdrop from "./ModalBackdrop";

/**
 * The third-party licence notices, read from the copy shipped inside the app.
 *
 * The file is generated by `scripts/third-party.py` and emitted into the
 * frontend bundle by a vite plugin, so what this shows is the licence set of
 * the build it is running in, not of whatever `main` looked like when the
 * release was cut.
 *
 * Fetched on open rather than imported: it is around 650 KB of licence text,
 * and importing it would put all of that in the startup bundle to serve a panel
 * most people open once, if ever.
 */
export default function NoticesDialog({ onClose }: { onClose: () => void }) {
  const [text, setText] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);
  useModalKeys(onClose);

  useEffect(() => {
    let live = true;
    fetch("/THIRD-PARTY.md")
      .then((r) => (r.ok ? r.text() : Promise.reject(new Error(String(r.status)))))
      .then((t) => { if (live) setText(t); })
      .catch(() => { if (live) setFailed(true); });
    return () => { live = false; };
  }, []);

  const html = useMemo(() => (text ? renderMarkdown(text, { labelFences: true }) : ""), [text]);

  return (
    <ModalBackdrop onBackdropClick={onClose}>
      <div
        className="modal modal-notices"
        role="dialog"
        aria-modal="true"
        aria-label="Third-party notices"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="modal-head">
          <div className="modal-head-text">
            <h3>Third-party notices</h3>
            <p className="modal-sub">
              The software inside Agency, and the licences it is used under.
            </p>
          </div>
          <button type="button" className="modal-x" onClick={onClose}>✕</button>
        </div>
        <div className="modal-body modal-notices-body">
          {failed ? (
            <p className="settings-section-hint">
              Couldn't read the notices file from this build. It is also in the
              repository, as THIRD-PARTY.md.
            </p>
          ) : text === null ? (
            <p className="settings-section-hint">Loading…</p>
          ) : (
            <div className="md" onClick={onMarkdownLinkClick} dangerouslySetInnerHTML={{ __html: html }} />
          )}
        </div>
      </div>
    </ModalBackdrop>
  );
}
